"""Seed the database with ~30 real commercial properties across 5 Southern California counties.

These are real addresses for mid-size commercial properties (warehouses, office parks,
strip malls, distribution centers, industrial buildings) -- the kind a solar installer
would actually target.

NOTE: The current Property model does not have a `stories` column.  Each dict below
      includes a `stories` key for reference; the INSERT statement omits it so it works
      against the existing schema.  If you add a `stories` column via Alembic, uncomment
      the relevant lines in the INSERT.

APN format by county (plausible examples, not assessor-verified):
  Los Angeles   : 0000-000-000   (book-page-parcel, 4-3-3)
  Orange        : 000-000-00     (3-3-2 with optional -00 suffix)
  San Diego     : 000-000-00-00  (3-3-2-2, ten digits)
  Riverside     : 000-000-000    (3-3-3)
  San Bernardino: 0000-000-00    (4-3-2)
"""

import asyncio
import uuid

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from solarpros.config import settings

# ---------------------------------------------------------------------------
# Real commercial properties across 5 SoCal counties
# ---------------------------------------------------------------------------
PROPERTIES: list[dict] = [
    # ======================================================================
    # LOS ANGELES COUNTY  (9 properties)
    # ======================================================================
    {
        "id": str(uuid.uuid4()),
        "apn": "6207-014-028",
        "address": "4593 E 49th St",
        "city": "Vernon",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90058",
        "latitude": 33.9926,
        "longitude": -118.1952,
        "year_built": 1989,
        "building_sqft": 137583.0,
        "roof_sqft": 55000.0,
        "stories": 1,
        "zoning": "M-2",
        "building_type": "Warehouse",
        "owner_name_raw": "Prologis Inc",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "6365-021-009",
        "address": "6929 E Slauson Ave",
        "city": "Commerce",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90040",
        "latitude": 33.9830,
        "longitude": -118.1399,
        "year_built": 1975,
        "building_sqft": 86236.0,
        "roof_sqft": 42000.0,
        "stories": 1,
        "zoning": "M-2",
        "building_type": "Industrial",
        "owner_name_raw": "Slauson Commerce Center LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "8042-017-033",
        "address": "14530 Anson Ave",
        "city": "Santa Fe Springs",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90670",
        "latitude": 33.9291,
        "longitude": -118.0576,
        "year_built": 1973,
        "building_sqft": 35350.0,
        "roof_sqft": 18000.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Industrial",
        "owner_name_raw": "Anson Avenue Properties LP",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "8035-024-015",
        "address": "14944 Shoemaker Ave",
        "city": "Santa Fe Springs",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90670",
        "latitude": 33.9340,
        "longitude": -118.0518,
        "year_built": 1978,
        "building_sqft": 85950.0,
        "roof_sqft": 40000.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Warehouse",
        "owner_name_raw": "Shoemaker Industrial LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "7330-011-052",
        "address": "263 E Gardena Blvd",
        "city": "Carson",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90248",
        "latitude": 33.8654,
        "longitude": -118.2569,
        "year_built": 1977,
        "building_sqft": 55238.0,
        "roof_sqft": 28000.0,
        "stories": 1,
        "zoning": "M-2",
        "building_type": "Industrial",
        "owner_name_raw": "Carson Gardena Industrial Partners",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "6119-018-042",
        "address": "16920 S Figueroa St",
        "city": "Gardena",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90248",
        "latitude": 33.8706,
        "longitude": -118.2811,
        "year_built": 1984,
        "building_sqft": 25120.0,
        "roof_sqft": 12500.0,
        "stories": 2,
        "zoning": "C-2",
        "building_type": "Office",
        "owner_name_raw": "Figueroa Office Associates",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "7403-023-018",
        "address": "17405 Valley View Ave",
        "city": "Cerritos",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90703",
        "latitude": 33.8695,
        "longitude": -118.0792,
        "year_built": 1970,
        "building_sqft": 400000.0,
        "roof_sqft": 60000.0,
        "stories": 1,
        "zoning": "M-2",
        "building_type": "Warehouse",
        "owner_name_raw": "Valley View Industrial Park LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "7404-009-024",
        "address": "16028 Marquardt Ave",
        "city": "Cerritos",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90703",
        "latitude": 33.8770,
        "longitude": -118.0721,
        "year_built": 1997,
        "building_sqft": 123058.0,
        "roof_sqft": 48000.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Warehouse",
        "owner_name_raw": "Marquardt Distribution LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "8149-003-037",
        "address": "14141 Alondra Blvd",
        "city": "Santa Fe Springs",
        "county": "Los Angeles",
        "state": "CA",
        "zip_code": "90670",
        "latitude": 33.9137,
        "longitude": -118.0456,
        "year_built": 1968,
        "building_sqft": 181324.0,
        "roof_sqft": 58000.0,
        "stories": 1,
        "zoning": "M-2",
        "building_type": "Warehouse",
        "owner_name_raw": "Alondra Commerce Center LP",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    # ======================================================================
    # ORANGE COUNTY  (6 properties)
    # ======================================================================
    {
        "id": str(uuid.uuid4()),
        "apn": "439-132-08",
        "address": "1821 E Dyer Rd",
        "city": "Santa Ana",
        "county": "Orange",
        "state": "CA",
        "zip_code": "92705",
        "latitude": 33.7018,
        "longitude": -117.8409,
        "year_built": 1986,
        "building_sqft": 126251.0,
        "roof_sqft": 32000.0,
        "stories": 3,
        "zoning": "C-2",
        "building_type": "Office",
        "owner_name_raw": "Irvine Corporate Center LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "446-091-15",
        "address": "20 Corporate Park",
        "city": "Irvine",
        "county": "Orange",
        "state": "CA",
        "zip_code": "92606",
        "latitude": 33.6946,
        "longitude": -117.8281,
        "year_built": 1989,
        "building_sqft": 57194.0,
        "roof_sqft": 19000.0,
        "stories": 3,
        "zoning": "C-1",
        "building_type": "Office",
        "owner_name_raw": "Olen Commercial Realty Corp",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "446-153-22",
        "address": "2 Executive Cir",
        "city": "Irvine",
        "county": "Orange",
        "state": "CA",
        "zip_code": "92614",
        "latitude": 33.6870,
        "longitude": -117.8548,
        "year_built": 1985,
        "building_sqft": 126531.0,
        "roof_sqft": 42000.0,
        "stories": 2,
        "zoning": "C-1",
        "building_type": "Office",
        "owner_name_raw": "Venture Park Associates LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "669-181-04",
        "address": "30900 Rancho Viejo Rd",
        "city": "San Juan Capistrano",
        "county": "Orange",
        "state": "CA",
        "zip_code": "92675",
        "latitude": 33.4863,
        "longitude": -117.6478,
        "year_built": 1991,
        "building_sqft": 92000.0,
        "roof_sqft": 24000.0,
        "stories": 3,
        "zoning": "C-2",
        "building_type": "Office",
        "owner_name_raw": "CBRE Group Inc",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "072-492-11",
        "address": "1165 W Ball Rd",
        "city": "Anaheim",
        "county": "Orange",
        "state": "CA",
        "zip_code": "92802",
        "latitude": 33.8084,
        "longitude": -117.9372,
        "year_built": 1994,
        "building_sqft": 145000.0,
        "roof_sqft": 52000.0,
        "stories": 1,
        "zoning": "C-3",
        "building_type": "Retail Center",
        "owner_name_raw": "Anaheim Plaza Partners LP",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "143-371-06",
        "address": "17222 Beach Blvd",
        "city": "Huntington Beach",
        "county": "Orange",
        "state": "CA",
        "zip_code": "92647",
        "latitude": 33.7227,
        "longitude": -117.9976,
        "year_built": 1982,
        "building_sqft": 16604.0,
        "roof_sqft": 8300.0,
        "stories": 1,
        "zoning": "C-2",
        "building_type": "Retail Center",
        "owner_name_raw": "Beach Boulevard Retail LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    # ======================================================================
    # SAN DIEGO COUNTY  (6 properties)
    # ======================================================================
    {
        "id": str(uuid.uuid4()),
        "apn": "646-050-18-00",
        "address": "6995 Calle De Linea",
        "city": "San Diego",
        "county": "San Diego",
        "state": "CA",
        "zip_code": "92154",
        "latitude": 32.5558,
        "longitude": -117.0295,
        "year_built": 1998,
        "building_sqft": 102875.0,
        "roof_sqft": 48000.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Warehouse",
        "owner_name_raw": "Otay Distribution Partners LP",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "361-201-07-00",
        "address": "5715 Kearny Villa Rd",
        "city": "San Diego",
        "county": "San Diego",
        "state": "CA",
        "zip_code": "92123",
        "latitude": 32.8242,
        "longitude": -117.1466,
        "year_built": 1987,
        "building_sqft": 109082.0,
        "roof_sqft": 52000.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Industrial",
        "owner_name_raw": "Kearny Mesa Business Center LP",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "362-110-24-00",
        "address": "4000 Ruffin Rd",
        "city": "San Diego",
        "county": "San Diego",
        "state": "CA",
        "zip_code": "92123",
        "latitude": 32.8197,
        "longitude": -117.1395,
        "year_built": 1982,
        "building_sqft": 57642.0,
        "roof_sqft": 28000.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Warehouse",
        "owner_name_raw": "Ruffin Road Industrial LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "167-410-33-00",
        "address": "5935 Darwin Ct",
        "city": "Carlsbad",
        "county": "San Diego",
        "state": "CA",
        "zip_code": "92008",
        "latitude": 33.1490,
        "longitude": -117.3057,
        "year_built": 2001,
        "building_sqft": 54351.0,
        "roof_sqft": 27000.0,
        "stories": 2,
        "zoning": "C-2",
        "building_type": "Office",
        "owner_name_raw": "Carlsbad Oaks North LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "231-082-15-00",
        "address": "1265 Laurel Tree Ln",
        "city": "Carlsbad",
        "county": "San Diego",
        "state": "CA",
        "zip_code": "92011",
        "latitude": 33.0942,
        "longitude": -117.2785,
        "year_built": 1999,
        "building_sqft": 25021.0,
        "roof_sqft": 12500.0,
        "stories": 2,
        "zoning": "C-1",
        "building_type": "Office",
        "owner_name_raw": "Laurel Tree Business Park LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "644-040-22-00",
        "address": "690 Otay Lakes Rd",
        "city": "Chula Vista",
        "county": "San Diego",
        "state": "CA",
        "zip_code": "91910",
        "latitude": 32.6241,
        "longitude": -117.0127,
        "year_built": 2012,
        "building_sqft": 12700.0,
        "roof_sqft": 6200.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Warehouse",
        "owner_name_raw": "Otay Lakes Commercial LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    # ======================================================================
    # RIVERSIDE COUNTY  (5 properties)
    # ======================================================================
    {
        "id": str(uuid.uuid4()),
        "apn": "486-190-017",
        "address": "24950 Grove View Rd",
        "city": "Moreno Valley",
        "county": "Riverside",
        "state": "CA",
        "zip_code": "92551",
        "latitude": 33.8880,
        "longitude": -117.2065,
        "year_built": 2007,
        "building_sqft": 426700.0,
        "roof_sqft": 60000.0,
        "stories": 1,
        "zoning": "M-2",
        "building_type": "Warehouse",
        "owner_name_raw": "Grove View Logistics LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "316-210-009",
        "address": "300 Palmyrita Ave",
        "city": "Riverside",
        "county": "Riverside",
        "state": "CA",
        "zip_code": "92507",
        "latitude": 33.9538,
        "longitude": -117.3614,
        "year_built": 2005,
        "building_sqft": 174000.0,
        "roof_sqft": 55000.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Warehouse",
        "owner_name_raw": "Logistics Plus Inc",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "111-320-004",
        "address": "400 Ramona Ave",
        "city": "Corona",
        "county": "Riverside",
        "state": "CA",
        "zip_code": "92879",
        "latitude": 33.8751,
        "longitude": -117.5648,
        "year_built": 1983,
        "building_sqft": 37664.0,
        "roof_sqft": 19000.0,
        "stories": 2,
        "zoning": "C-2",
        "building_type": "Office",
        "owner_name_raw": "Corona Mall Professional Centre LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "921-780-022",
        "address": "41707 Winchester Rd",
        "city": "Temecula",
        "county": "Riverside",
        "state": "CA",
        "zip_code": "92590",
        "latitude": 33.5123,
        "longitude": -117.1529,
        "year_built": 2004,
        "building_sqft": 25694.0,
        "roof_sqft": 13000.0,
        "stories": 2,
        "zoning": "C-1",
        "building_type": "Office",
        "owner_name_raw": "Winchester Business Park LP",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "290-130-041",
        "address": "7887 Mission Grove Pkwy S",
        "city": "Riverside",
        "county": "Riverside",
        "state": "CA",
        "zip_code": "92508",
        "latitude": 33.8912,
        "longitude": -117.3254,
        "year_built": 2006,
        "building_sqft": 70964.0,
        "roof_sqft": 35000.0,
        "stories": 2,
        "zoning": "C-2",
        "building_type": "Medical Office",
        "owner_name_raw": "Mission Grove Medical Partners LP",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    # ======================================================================
    # SAN BERNARDINO COUNTY  (5 properties)
    # ======================================================================
    {
        "id": str(uuid.uuid4()),
        "apn": "0229-202-18",
        "address": "10681 Production Ave",
        "city": "Fontana",
        "county": "San Bernardino",
        "state": "CA",
        "zip_code": "92337",
        "latitude": 34.0726,
        "longitude": -117.5159,
        "year_built": 2006,
        "building_sqft": 200000.0,
        "roof_sqft": 60000.0,
        "stories": 1,
        "zoning": "M-2",
        "building_type": "Warehouse",
        "owner_name_raw": "Sierra Business Park LP",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "0133-371-25",
        "address": "773 Foisy St",
        "city": "San Bernardino",
        "county": "San Bernardino",
        "state": "CA",
        "zip_code": "92408",
        "latitude": 34.0856,
        "longitude": -117.2674,
        "year_built": 1985,
        "building_sqft": 42000.0,
        "roof_sqft": 21000.0,
        "stories": 1,
        "zoning": "M-1",
        "building_type": "Warehouse",
        "owner_name_raw": "Foisy Street Properties LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "0134-261-09",
        "address": "328 Commercial Rd",
        "city": "San Bernardino",
        "county": "San Bernardino",
        "state": "CA",
        "zip_code": "92408",
        "latitude": 34.0802,
        "longitude": -117.2580,
        "year_built": 1979,
        "building_sqft": 65000.0,
        "roof_sqft": 32000.0,
        "stories": 1,
        "zoning": "M-2",
        "building_type": "Industrial",
        "owner_name_raw": "Commercial Road Holdings Inc",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "0210-143-33",
        "address": "1275 W Foothill Blvd",
        "city": "Upland",
        "county": "San Bernardino",
        "state": "CA",
        "zip_code": "91786",
        "latitude": 34.0976,
        "longitude": -117.6580,
        "year_built": 1988,
        "building_sqft": 18700.0,
        "roof_sqft": 9500.0,
        "stories": 2,
        "zoning": "C-2",
        "building_type": "Office",
        "owner_name_raw": "Foothill Professional Plaza LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
    {
        "id": str(uuid.uuid4()),
        "apn": "0169-101-47",
        "address": "26871 San Bernardino Ave",
        "city": "Redlands",
        "county": "San Bernardino",
        "state": "CA",
        "zip_code": "92374",
        "latitude": 34.0430,
        "longitude": -117.1621,
        "year_built": 1995,
        "building_sqft": 34000.0,
        "roof_sqft": 17000.0,
        "stories": 2,
        "zoning": "C-1",
        "building_type": "Office",
        "owner_name_raw": "Nevada Corporate Center LLC",
        "is_commercial": True,
        "meets_roof_min": True,
    },
]


# ---------------------------------------------------------------------------
# Async seed function (mirrors existing seed_mock_data.py pattern)
# ---------------------------------------------------------------------------
async def seed():
    engine = create_async_engine(settings.database_url)
    session_factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with session_factory() as session:
        # Check if data already exists
        result = await session.execute(text("SELECT COUNT(*) FROM properties"))
        count = result.scalar()
        if count and count > 0:
            print(f"Database already has {count} properties. Skipping seed.")
            return

        inserted = 0
        for prop in PROPERTIES:
            lat = prop["latitude"]
            lng = prop["longitude"]
            await session.execute(
                text("""
                    INSERT INTO properties (
                        id, apn, county, address, city, state, zip_code,
                        latitude, longitude, location,
                        zoning, building_type, building_sqft, roof_sqft,
                        year_built, owner_name_raw, is_commercial, meets_roof_min,
                        created_at, updated_at
                    ) VALUES (
                        :id, :apn, :county, :address, :city, :state, :zip_code,
                        :latitude, :longitude,
                        ST_SetSRID(ST_MakePoint(:longitude, :latitude), 4326),
                        :zoning, :building_type, :building_sqft, :roof_sqft,
                        :year_built, :owner_name_raw, :is_commercial, :meets_roof_min,
                        NOW(), NOW()
                    )
                """),
                {
                    "id": prop["id"],
                    "apn": prop["apn"],
                    "county": prop["county"],
                    "address": prop["address"],
                    "city": prop["city"],
                    "state": prop["state"],
                    "zip_code": prop["zip_code"],
                    "latitude": lat,
                    "longitude": lng,
                    "zoning": prop["zoning"],
                    "building_type": prop["building_type"],
                    "building_sqft": prop["building_sqft"],
                    "roof_sqft": prop["roof_sqft"],
                    "year_built": prop["year_built"],
                    "owner_name_raw": prop["owner_name_raw"],
                    "is_commercial": prop["is_commercial"],
                    "meets_roof_min": prop["meets_roof_min"],
                },
            )
            inserted += 1

        await session.commit()
        print(f"Seeded {inserted} real commercial properties across 5 counties.\n")

        # Print summary per county
        counties = {}
        for p in PROPERTIES:
            c = p["county"]
            if c not in counties:
                counties[c] = {"total": 0, "types": {}}
            counties[c]["total"] += 1
            bt = p["building_type"]
            counties[c]["types"][bt] = counties[c]["types"].get(bt, 0) + 1

        for county, info in counties.items():
            type_str = ", ".join(f"{v} {k}" for k, v in info["types"].items())
            print(f"  {county}: {info['total']} properties ({type_str})")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
